"use client"

import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import { ReactLenis, useLenis } from 'lenis/react'

import { Providers } from "./providers";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const lenis = useLenis(({ scroll }) => {
    // called every scroll
  })
  
  return (

    <ReactLenis root>
    <html lang="en" className={oswald.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
    </ReactLenis>
  );
}
